# -*- coding: utf-8 -*-
# (c) Copyright 2019 Sensirion AG, Switzerland

##############################################################################
##############################################################################
#                 _____         _    _ _______ _____ ____  _   _
#                / ____|   /\  | |  | |__   __|_   _/ __ \| \ | |
#               | |       /  \ | |  | |  | |    | || |  | |  \| |
#               | |      / /\ \| |  | |  | |    | || |  | | . ` |
#               | |____ / ____ \ |__| |  | |   _| || |__| | |\  |
#                \_____/_/    \_\____/   |_|  |_____\____/|_| \_|
#
#     THIS FILE IS AUTOMATICALLY GENERATED AND MUST NOT BE EDITED MANUALLY!
#
# Generator:    sensirion-shdlc-interface-generator 0.4.0
# Product:      Sensor Bridge
# Version:      0.1.0
#
##############################################################################
##############################################################################

# flake8: noqa

from __future__ import absolute_import, division, print_function
from .device_information import \
    SensorBridgeCmdGetProductType, \
    SensorBridgeCmdGetProductName, \
    SensorBridgeCmdGetArticleCode, \
    SensorBridgeCmdGetSerialNumber
from .get_version import \
    SensorBridgeCmdGetVersion
from .slave_address import \
    SensorBridgeCmdSetSlaveAddress
from .baudrate import \
    SensorBridgeCmdSetBaudrate
from .set_port_voltage import \
    SensorBridgeCmdSetPortVoltage
from .port_voltage_on_off import \
    SensorBridgeCmdPortVoltageOnOff
from .set_i2c_frequency import \
    SensorBridgeCmdSetI2cFrequency
from .i2c_scan import \
    SensorBridgeCmdI2cScan
from .i2c_transceive import \
    SensorBridgeCmdFirstTransceive, \
    SensorBridgeCmdSubsequentTransceive
from .i2c_repeated_transceive import \
    SensorBridgeCmdI2cRepeatedTransceive
from .read_buffer import \
    SensorBridgeCmdReadBuffer
from .stop_repeated_transceive import \
    SensorBridgeCmdStopRepeatedTransceive
from .spi_config import \
    SensorBridgeCmdSpiConfig
from .spi_transceive import \
    SensorBridgeCmdSpiTransceive
from .blink import \
    SensorBridgeCmdBlink
from .analog_measurement import \
    SensorBridgeCmdAnalogMeasurement
from .firmware_update import \
    SensorBridgeCmdEnterBootloader, \
    SensorBridgeCmdStartUpdate, \
    SensorBridgeCmdUpdateData, \
    SensorBridgeCmdStopUpdate
